# Generated by Django 3.2.4 on 2022-09-01 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20220901_1541'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contectus',
            new_name='contactus',
        ),
    ]
