# Generated by Django 3.2.4 on 2023-05-04 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_mcart_cdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myproduct',
            name='pcolor',
        ),
        migrations.RemoveField(
            model_name='myproduct',
            name='psize',
        ),
        migrations.AddField(
            model_name='myproduct',
            name='name',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
