# Generated by Django 3.2.4 on 2023-05-20 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20230504_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='MainCategoryName',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
